AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'spec/support/**/*'
    - 'spec/**/*'
    - 'lib/date_refinements.rb'
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Metrics/AbcSize:
  Max: 25
